version: "3.9"

services:
  dcsp-docs-builder:
    build: 
      context: ./dockerfiles/app
      dockerfile: Dockerfile
      target: dev
    container_name: dcsp-docs-builder
    #restart: unless-stopped
    volumes:
      - ./:/dcsp
      - projects:/projects
      - documentation-pages:/documentation-pages
    env_file:
      - .env_dev
    working_dir: /dcsp/app
    depends_on:
      - dcsp-postgres
    networks: 
      - cross-site
    entrypoint: bash PID_1.sh

  dcsp-postgres:
    image: postgres:latest
    container_name: dcsp-postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env_dev
    #environment:
    #  POSTGRES_USER: ${POSTGRES_USER}
    #  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    #  POSTGRES_DB: ${POSTGRES_DB}
    networks: 
      - cross-site

  dcsp-nginx:
    image: nginx:alpine
    container_name: dcsp-nginx
    #restart: unless-stopped
    ports:
      - "443:443"
      - "80:80"
      - "9000:9000"
    volumes:
      - ./app/dcsp/static/:/static/:ro
      - ./nginx/dev/:/etc/nginx/:ro
      - documentation-pages:/documentation-pages:ro
      - ./logs/nginx/:/var/log/nginx/
    depends_on:
      - dcsp-docs-builder
    networks: 
      - cross-site

volumes:
  postgres_data:
  projects:
  documentation-pages:

networks:
  cross-site:
    driver: bridge  