version: "3.9"

services:
  dcsp-docs-builder-cicd:
    image: cotswoldsmaker/dcsp-doc-builder-cicd:latest
    container_name: dcsp-docs-builder-cicd
    restart: "no"
    volumes:
      - ./:/dcsp
      - projects:/projects
      - documentation-pages:/documentation-pages
    env_file:
      - .env_cicd
    working_dir: /dcsp/cicd
    networks: 
      - cross-site-cicd
    entrypoint: bash PID_1_cicd.sh

  dcsp-postgres-cicd:
    image: postgres:latest
    container_name: dcsp-postgres-cicd
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env_cicd
    #environment:
    #  POSTGRES_USER: ${POSTGRES_USER}
    #  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    #  POSTGRES_DB: ${POSTGRES_DB}
    networks: 
      - cross-site-cicd

volumes:
  postgres_data:
  projects:
  documentation-pages:

networks:
  cross-site-cicd:
    driver: bridge  