version: "3.9"

services:
  dcsp-docs-builder-prod:
    image: cotswoldsmaker/dcsp-doc-builder-prod:latest
    container_name: dcsp-docs-builder-prod
    restart: unless-stopped
    volumes:
      - ./:/dcsp
      - projects:/projects
      - documentation-pages:/documentation-pages
    env_file:
      - .env_prod
    working_dir: /dcsp/app
    depends_on:
      - dcsp-postgres-prod
    networks: 
      - cross-site
    entrypoint: bash PID_1.sh
  
  dcsp-postgres-prod:
    image: postgres:latest
    container_name: dcsp-postgres-prod
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env_prod
    networks: 
      - cross-site
  
  dcsp-nginx-prod:
    image: nginx:alpine
    container_name: dcsp-nginx-prod
    restart: unless-stopped
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./app/dcsp/static:/static:ro
      - documentation-pages:/documentation-pages:ro
      - ./logs/nginx:/var/log/nginx

      - ./nginx/prod:/etc/nginx:ro
      - ./certbot/www:/var/www/certbot:ro
      - ./certbot/conf:/etc/nginx/ssl:ro
      
    depends_on:
      - dcsp-docs-builder-prod
    networks: 
      - cross-site

  certbot-prod:
    image: certbot/certbot
    container_name: certbot-prod
    restart: no
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

volumes:
  postgres_data:
  projects:
  documentation-pages:


networks:
  documentation-pages:
  cross-site:
    driver: bridge