version: "3.9"

services:
  dcsp-docs-builder-prod:
    extends:
      file: docker-compose-dev.yml
      service: dcsp-docs-builder
  
  dcsp-postgres-prod:
    extends:
      file: docker-compose-dev.yml
      service: dcsp-postgres

  dcsp-nginx-prod:
    extends:
      file: docker-compose-dev.yml
      service: dcsp-nginx

volumes:
  postgres_data:

networks:
  cross-site:
    driver: bridge