version: "3.9"

services:
  dcsp-docs-builder:
    build: 
      context: ./dockerfiles/app
      dockerfile: Dockerfile
    container_name: dcsp-docs-builder
    #restart: unless-stopped
    #ports:
    #  - "80:80"
    #  - "443:443"
    #  - "9000:9000"
    volumes:
      - ./:/dcsp
      # TODO #36 - These will need to be converted into a volume at some point
      - ../projects:/projects
      - ../documentation-pages:/documentation-pages
      #- ../mkdocstrings:/usr/local/lib/python3.10/dist-packages/mkdocstrings
      #- ../mkdocstrings_handlers:/usr/local/lib/python3.10/dist-packages/mkdocstrings_handlers
      #- ../griffe:/usr/local/lib/python3.10/dist-packages/griffe
    env_file:
      - .env
    working_dir: /dcsp/app
    depends_on:
      - dcsp-postgres
    networks: 
      - cross-site
    entrypoint: bash PID_1_loop.sh

  dcsp-postgres:
    image: postgres:latest
    container_name: dcsp-postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks: 
      - cross-site

  dcsp-nginx:
    image: nginx:alpine
    container_name: dcsp-nginx
    #restart: unless-stopped
    ports:
      - "443:443"
      - "80:80"
      - "9000:9000"
    volumes:
      - ./app/dcsp/static/:/static/:ro
      - ./nginx/dev/:/etc/nginx/:ro
      - ../documentation-pages:/documentation-pages
      - ./logs/nginx/:/var/log/nginx/
    depends_on:
      - dcsp-docs-builder
    networks: 
      - cross-site

volumes:
  postgres_data:

networks:
  cross-site:
    driver: bridge  