version: "3.9"

services:
  dcsp-docs-builder-prod:
    image: cotswoldsmaker/dcsp-doc-builder-prod:latest
    container_name: dcsp-docs-builder-prod
    restart: "always"
    volumes:
      - ./:/dcsp
      - projects:/projects
      - documentation-pages:/documentation-pages
    env_file:
      - .env
    working_dir: /dcsp/app
    depends_on:
      - dcsp-postgres-prod
    networks: 
      - cross-site
    entrypoint: bash PID_1.sh
  
  dcsp-postgres-prod:
    image: postgres:latest
    container_name: dcsp-postgres-prod
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks: 
      - cross-site
  
  dcsp-nginx-prod:
    image: nginx:alpine
    container_name: dcsp-nginx-prod
    restart: unless-stopped
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./app/dcsp/static/:/static/:ro
      - ./nginx/prod/:/etc/nginx/:ro
      - ./logs/nginx/:/var/log/nginx/
    depends_on:
      - dcsp-docs-builder-prod
    networks: 
      - cross-site

  #dcsp-certbot:
  #  image: certbot/certbot:latest
  #  volumes:
  #    - /var/certbot/conf:/etc/letsencrypt/:rw
  #    - /var/certbot/www/:/var/www/certbot/:rw
  #  depends_on:
  #    - nginx
  #  networks: 
  #    - cross-site

volumes:
  postgres_data:
  users_docs:

networks:
  cross-site:
    driver: bridge