version: "3.9"

services:
  dcsp-docs-builder:
    build: ./dockerfiles/app
    container_name: dcsp-docs-builder
    #restart: unless-stopped
    #ports:
    #  - "80:80"
    #  - "443:443"
    #  - "9000:9000"
    volumes:
      - ./:/dcsp
    env_file:
      - .env
    working_dir: /dcsp/app
    depends_on:
      - dcsp-postgres
    networks: 
      - cross-site
    entrypoint: bash PID_1.sh

  dcsp-postgres:
    image: postgres:latest
    container_name: dcsp-postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    networks: 
      - cross-site

  dcsp-nginx:
    image: nginx:alpine
    container_name: dcsp-nginx
    #restart: unless-stopped
    ports:
      - "443:443"
      - "80:80"
      - "9000:9000"
    volumes:
      - ./app/dcsp/static/:/static/
      - ./nginx/dev/:/etc/nginx/
      - ./logs/nginx/:/var/log/nginx/
    depends_on:
      - dcsp-docs-builder
    networks: 
      - cross-site

volumes:
  postgres_data:

networks:
  cross-site:
    driver: bridge  