version: "3.9"

services:
  dcsp-docs-builder-cicd:
    image: cotswoldsmaker/dcsp:cicd
    container_name: dcsp-docs-builder-cicd
    restart: "no"
    volumes:
      - ./:/dcsp
    env_file:
      - .env
    working_dir: /dcsp/app
    entrypoint: bash PID_1_cicd.sh

# --abort-on-container-exit
# --remove-orphans
