name: cicd_main

on:
  push:
    branches:
      - master
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/deploy.key
          chmod 600 ~/.ssh/deploy.key
          cat >>~/.ssh/config <<END
          Host deploy
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/deploy.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.DEPLOY_SSH_USER }}
          SSH_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
          SSH_HOST: ${{ secrets.DEPLOY_SSH_HOST }}

      - name: Login to Docker
        run: ssh deploy 'docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}'

      - name: Pull image from Dockerhub
        run: ssh deploy 'docker pull cotswoldsmaker/dcsp-doc-builder-prod:latest'

      - name: Git pull
        run: ssh deploy 'cd /src/digital-clinical-safety-platform && git pull'
      
      - name: Stop docker-compose
        run: ssh deploy 'cd /src/digital-clinical-safety-platform && docker compose -f docker-compose-prod.yml down'

      - name: Restart docker-compose
        run: ssh deploy 'cd /src/digital-clinical-safety-platform && docker compose -f docker-compose-prod.yml up -d'
      
      - name: Makemigrations and migrate Django and restart Gunvicorn
        run: ssh deploy 'docker exec dcsp-docs-builder-prod sh mmr.sh'


  mkdocs-documents:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: pip install -r ./mkdocs_dcsp/requirements_mkdocs_dcsp.txt
      - run: mkdocs gh-deploy --force --config-file './mkdocs_dcsp/mkdocs.yml'
