name: cicd
on:
  push:
    branches:
      - master 
      - main
permissions:
  contents: write

jobs:
  Image-build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build cicd image
        uses: docker/build-push-action@v5
        with:
          context: ./dockerfiles/app/
          file: ./dockerfiles/app/Dockerfile-dev-cicd
          tags: cotswoldsmaker/dcsp:cicd
          #push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64
      
      - name: Make .env file
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
          envkey_ALLOW_HOSTS: ${{ secrets.ALLOW_HOSTS }}
          envkey_DEBUG: False
          envkey_EMAIL_HOST_USER: none
          envkey_EMAIL_HOST_PASSWORD: none
          envkey_POSTGRES_USER: dcsp
          envkey_POSTGRES_PASSWORD: a_password
          envkey_POSTGRES_DB: 'cicd_database'
          envkey_POSTGRES_ENGINE: 'django.db.backends.postgresql'
          envkey_POSTGRES_PORT: '5432'
          file_name: .env

      - name: Testing inside Docker container
        run: >
          docker-compose -f docker-compose-cicd-docs-builder.yml up --exit-code-from dcsp-docs-builder-cicd
      
      - name: Build cicd image
        uses: docker/build-push-action@v5
        with:
          context: ./dockerfiles/app/
          file: ./dockerfiles/app/Dockerfile-prod
          tags: cotswoldsmaker/dcsp:prod
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64
  

  deploy:
    runs-on: ubuntu-latest
    needs: Image-build-and-test
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/deploy.key
          chmod 600 ~/.ssh/deploy.key
          cat >>~/.ssh/config <<END
          Host deploy
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/deploy.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.DEPLOY_SSH_USER }}
          SSH_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
          SSH_HOST: ${{ secrets.DEPLOY_SSH_HOST }}
          # ssh-keygen -t rsa -b 4096 -C "your_email@example.com"

      - name: Login to Docker
        run: ssh deploy 'docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}'

      - name: Pull image from Dockerhub
        run: ssh deploy 'docker pull cotswoldsmaker/dcsp:latest'

      - name: Git pull
        run: ssh deploy 'cd /src/digital-clinical-safety-platform && git pull'
      
      - name: Stop docker-compose
        run: ssh deploy 'cd /src/digital-clinical-safety-platform && docker compose -f docker-compose-prod.yml down'

      - name: Start docker-compose again
        run: ssh deploy 'cd /src/digital-clinical-safety-platform && docker compose -f docker-compose-prod.yml up -d'
  
  
  mkdocs-documents:
    runs-on: ubuntu-latest
    needs: Image-build-and-test
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: pip install -r ./mkdocs_dcsp/requirements_mkdocs_dcsp.txt
      - run: mkdocs gh-deploy --force --config-file './mkdocs_dcsp/mkdocs.yml'

          
      
      